### ISSUE TITLE
Result is bad

### ISSUE THREAD

**Issue by AINoise** [yxlu-0102/MP-SENet#14]
when I used  " python inference.py --checkpoint_file best_ckpt/g_best " for tested my noisy.wav, The result.wav is bad .The noise is still preserved. Did I make a mistake in my steps？

**Comment by yxlu-0102** [comment]
Is your noisy speech data from your own dataset or from the VoiceBank+DEMAND dataset? 
Does it at a sampling rate of 16 kHz?

**Comment by AINoise** [comment]
> Is your noisy speech data from your own dataset or from the VoiceBank+DEMAND dataset? Does it at a sampling rate of 16 kHz?

It's my dataset and 16kHz. But universality is required. Does it rely strongly on training data?

**Comment by yxlu-0102** [comment]
The universality is also related to the dataset size.
Our model was trained on the Voicebank+DEMAND dataset, which is not that big. 
You can fine-tune our model with your data for better performance.
