### ISSUE TITLE
训练的话，training.txt的内容，十分困惑

### ISSUE THREAD

**Issue by moshengmao** [yxlu-0102/MP-SENet#18]
您好，我下载了voicebank+demand数据集，28speakers这个，然后我把他们降采样到16khz，目录结构是train下面有11572的clean和noisy，test下面有824条的clean和noisy，

然后我把他们重新划分文件夹结构，如同项目中readme所说，我把test的824放到wavs_noisy和wavs_clean，然后把test.txt中是824条的路径（更新到本机的路径）。

但是如果我想要用voicebank训练的话，提示我没有training.txt文件，我想知道，我应该把11572条训练数据放到哪里，然后应该training.txt写什么内容，我有点没搞清楚。是不是放错文件夹了，还是怎么回事，我想知道作者是怎么设置文件夹的。

感谢！

**Comment by yxlu-0102** [comment]
我这个项目中是把所有的 train 或者 test 的语音放在一起的，clean 就放在 wav_clean 中，noisy 放在 wav_noisy 中，你也可以从 `dataset.py` 中更改数据读取的格式。
