### ISSUE TITLE
Wrong default path

### ISSUE THREAD

**Issue by TrilSiaWalt** [yxlu-0102/MP-SENet#22]
https://github.com/yxlu-0102/MP-SENet/blob/47d32fc6f8dbbda5676c48d177817133f947869c/train.py#L272
you may see that there should be "VoiceBank+DEMAND/wavs_clean" with the capital B instead of "Voicebank+DEMAND/wavs_clean"  with lower-case b

**Comment by yxlu-0102** [comment]
Thank you for pointing out our mistake, we have rectified it.
