### ISSUE TITLE
请问有什么降低MetricLoss的好方法吗

### ISSUE THREAD

**Issue by HenryPurcell3** [yxlu-0102/MP-SENet#27]
作者您好，我最近复现了您的实验，首先是loss容易到nan，看起来是梯度爆炸了，而且我的metricloss久久下不来一直在0.7几左右，请问应该怎么办了

**Comment by HenryPurcell3** [comment]
作者您好，我最近复现了您的实验，首先是loss容易到nan，看起来是梯度爆炸了，而且我的metricloss久久下不来一直在0.7几左右，请问应该怎么办了

**Comment by yxlu-0102** [comment]
loss 出现 nan 的话可以尝试提取相位的时候加上一个 bias:
<img width="610" alt="325847462-173663d0-a8c8-4853-80c2-7a950f909b51" src="https://github.com/yxlu-0102/MP-SENet/assets/82219664/590bb874-7c68-4a04-954a-e2d639eb0910">

**Comment by HenryPurcell3** [comment]
谢谢宝贝
