### ISSUE TITLE
Weights trained on DNS

### ISSUE THREAD

**Issue by Ludvig-Joborn** [yxlu-0102/MP-SENet#28]
Hi!

Fantastic work with the model and thank you for releasing the code!
I'd really appreciate if you could make available the weights after the model has been fine-tuned in speech enhancement on the DNS-dataset.

Thanks!

**Comment by yxlu-0102** [comment]
Hi, the journal version of MP-SENet is still under review now, we will release the weights trained on the DNS datasets after the paper is accepted.

**Comment by Ludvig-Joborn** [comment]
Awesome! Looking forward to the Paper release then! :+1:

**Comment by Sofonov** [comment]
Please, release the weights trained on the DNS data sets
