### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by hbwu-ntu** [yxlu-0102/MP-SENet#3]
Hi, your paper and code are excellent! I have learned a lot about speech enhancement from the paper, and I find your code to be very well-structured and clear. Thank you so much!

I have some questions:
1. Have you fulfilled the multi-gpu running. It seems the training will stuck in https://github.com/yxlu-0102/MP-SENet/blob/main/train.py#L146-L160. If not, maybe I can help you with this issue
2. What is the batch size, gpu type and training time for your experiments?

Thanks in advance.

**Comment by yxlu-0102** [comment]
Thank you for recognizing our work!

During the training process, we actually employed a multi-GPU strategy.<br> 
Personally, I used two NVIDIA 3090ti GPUs to train the MP-SENet like<br>
`CUDA_VISIBLE_DEVICES=0,1 python train.py --config config.json`

The batch size was set to 4, resulting in a batch size of 2 for each GPU.<br>
The training process is expected to take approximately 3 to 4 days.
