### ISSUE TITLE
Complex loss calculated using compressed magnitude

### ISSUE THREAD

**Issue by philgzl** [yxlu-0102/MP-SENet#32]
In the long-version paper, the magnitude loss is defined as a distance between the compressed magnitudes (Eq. 2). Meanwhile the complex loss is defined as a distance between the non-compressed complex representations of the signals (Eq. 8). However since the dataset class is returning a complex signal that uses the compressed magnitude [here](https://github.com/yxlu-0102/MP-SENet/blob/49745c1acd0026a4c8dfc757104c084cb1c74b50/datasets/dataset.py#L16), it seems to me that the complex loss actually uses compressed versions of the signals. Can you confirm?

**Comment by yxlu-0102** [comment]
Oops! You are right.

I did use the magnitude-compressed complex spectrum when calculating the loss. 

The description in the journal version is incorrect. We will correct it. Thank you for pointing it out!

**Comment by philgzl** [comment]
Great thanks!
