### ISSUE TITLE
Real-time or causal system

### ISSUE THREAD

**Issue by rohithmars** [yxlu-0102/MP-SENet#4]
Hello,

Thanks for releasing the code and other details.

Is the MP-SENet model causal? Is it possible to use it for real-time speech enhancement?

**Comment by yxlu-0102** [comment]
The MP-SENet model is non-causal and has latency. We attempted to use causal convolutions for phase prediction in other work, but employed additional knowledge distillation.

**Comment by yxlu-0102** [comment]
> > The MP-SENet model is non-causal and has latency. We attempted to use causal convolutions for phase prediction in other work, but employed additional knowledge distillation.
> 
> 主要是conformer不能frame by frame吧？

是的，我说的是另一个相位预测相关的工作没用到 attention.
