### ISSUE TITLE
Bandwidth extension checkpoint

### ISSUE THREAD

**Issue by RF5** [yxlu-0102/MP-SENet#5]
Hi authors, thank you for your amazing work! 

I was wondering: you mention in the full paper that MP-SENet can also be used for bandwidth extension. Do you have any plans to release the checkpoint / inference code for the bandwidth extension variant of MP-SENet? Thank you again for your work!

**Comment by yxlu-0102** [comment]
We will release the source code for the bandwidth extension task after our paper is accepted, thank you for your continued interest!

**Comment by RF5** [comment]
Thank you, I look forward to the release!
