### ISSUE TITLE
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV

### ISSUE THREAD

**Issue by emptygreen-w** [yxlu-0102/MP-SENet#7]
Hello,
thank you for providing the code.
However, I encountered the following issues while reproducing the code. May I ask if you are available to answer the following?
`Traceback (most recent call last):
  File "train.py", line 312, in <module>
    main()
  File "train.py", line 306, in main
    mp.spawn(train, nprocs=h.num_gpus, args=(a, h,))
  File "/home/wrl/miniconda3/envs/python37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/wrl/miniconda3/envs/python37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/wrl/miniconda3/envs/python37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 136, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV
`

**Comment by yxlu-0102** [comment]
I haven't encountered this type of issue before, perhaps it's related to your pytorch and anaconda versions.

**Comment by emptygreen-w** [comment]
Dear Author,


Thank you for responding to my inquiry. I will continue my research based on the direction you have provided.


Best regards,
Ruilin Wu





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yxlu-0102/MP-SENet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yxlu-0102/MP-SENet] torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV (Issue #7)





 
I haven't encountered this type of issue before, perhaps it's related to your pytorch and anaconda versions.

**Comment by TrilSiaWalt** [comment]
> Dear Author, Thank you for responding to my inquiry. I will continue my research based on the direction you have provided. Best regards, Ruilin Wu
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yxlu-0102/MP-SENet" ***@***.***&gt;; 发送时间:&nbsp;2023年10月5日(星期四) 晚上8:35 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yxlu-0102/MP-SENet] torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV (Issue #7) I haven't encountered this type of issue before, perhaps it's related to your pytorch and anaconda versions. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

have you find out the way to solve it?
